[project]
name = "teg-2025-elearning"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.6.0",
    "python-dotenv>=1.1.1",
]

[tool.uv.workspace]
members = [
    "src/4. Chains",
]
